//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Desgo_Xamarin.Droid.AmazonDesgoWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGestionUsuarioPortBinding", Namespace="http://servicios.desgo.com.ec/")]
    public partial class WSGestionUsuario : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarPersonasOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarFormularioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSGestionUsuario() {
            this.Url = "http://amazonwebservicedesgo-env.us-east-1.elasticbeanstalk.com:80/WSGestionUsuar" +
                "io";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event buscarPersonaCompletedEventHandler buscarPersonaCompleted;
        
        /// <remarks/>
        public event listarRolesCompletedEventHandler listarRolesCompleted;
        
        /// <remarks/>
        public event listarUsuariosCompletedEventHandler listarUsuariosCompleted;
        
        /// <remarks/>
        public event listarPersonasCompletedEventHandler listarPersonasCompleted;
        
        /// <remarks/>
        public event eliminarPersonaCompletedEventHandler eliminarPersonaCompleted;
        
        /// <remarks/>
        public event eliminarUsuarioCompletedEventHandler eliminarUsuarioCompleted;
        
        /// <remarks/>
        public event editarPersonaCompletedEventHandler editarPersonaCompleted;
        
        /// <remarks/>
        public event registrarUsuarioCompletedEventHandler registrarUsuarioCompleted;
        
        /// <remarks/>
        public event editarUsuarioCompletedEventHandler editarUsuarioCompleted;
        
        /// <remarks/>
        public event registrarFormularioCompletedEventHandler registrarFormularioCompleted;
        
        /// <remarks/>
        public event ValidarCompletedEventHandler ValidarCompleted;
        
        /// <remarks/>
        public event RegistrarCompletedEventHandler RegistrarCompleted;
        
        /// <remarks/>
        public event registrarUserCompletedEventHandler registrarUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public user login([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass) {
            object[] results = this.Invoke("login", new object[] {
                        user,
                        pass});
            return ((user)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string user, string pass) {
            this.loginAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void loginAsync(string user, string pass, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        user,
                        pass}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public user buscarPersona([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int iduser) {
            object[] results = this.Invoke("buscarPersona", new object[] {
                        iduser});
            return ((user)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPersonaAsync(int iduser) {
            this.buscarPersonaAsync(iduser, null);
        }
        
        /// <remarks/>
        public void buscarPersonaAsync(int iduser, object userState) {
            if ((this.buscarPersonaOperationCompleted == null)) {
                this.buscarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPersonaOperationCompleted);
            }
            this.InvokeAsync("buscarPersona", new object[] {
                        iduser}, this.buscarPersonaOperationCompleted, userState);
        }
        
        private void OnbuscarPersonaOperationCompleted(object arg) {
            if ((this.buscarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPersonaCompleted(this, new buscarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoUsuario[] listarRoles() {
            object[] results = this.Invoke("listarRoles", new object[0]);
            return ((tipoUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void listarRolesAsync() {
            this.listarRolesAsync(null);
        }
        
        /// <remarks/>
        public void listarRolesAsync(object userState) {
            if ((this.listarRolesOperationCompleted == null)) {
                this.listarRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarRolesOperationCompleted);
            }
            this.InvokeAsync("listarRoles", new object[0], this.listarRolesOperationCompleted, userState);
        }
        
        private void OnlistarRolesOperationCompleted(object arg) {
            if ((this.listarRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarRolesCompleted(this, new listarRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public user[] listarUsuarios([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int iduser) {
            object[] results = this.Invoke("listarUsuarios", new object[] {
                        iduser});
            return ((user[])(results[0]));
        }
        
        /// <remarks/>
        public void listarUsuariosAsync(int iduser) {
            this.listarUsuariosAsync(iduser, null);
        }
        
        /// <remarks/>
        public void listarUsuariosAsync(int iduser, object userState) {
            if ((this.listarUsuariosOperationCompleted == null)) {
                this.listarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarUsuariosOperationCompleted);
            }
            this.InvokeAsync("listarUsuarios", new object[] {
                        iduser}, this.listarUsuariosOperationCompleted, userState);
        }
        
        private void OnlistarUsuariosOperationCompleted(object arg) {
            if ((this.listarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarUsuariosCompleted(this, new listarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public persona[] listarPersonas([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int iduser) {
            object[] results = this.Invoke("listarPersonas", new object[] {
                        iduser});
            return ((persona[])(results[0]));
        }
        
        /// <remarks/>
        public void listarPersonasAsync(int iduser) {
            this.listarPersonasAsync(iduser, null);
        }
        
        /// <remarks/>
        public void listarPersonasAsync(int iduser, object userState) {
            if ((this.listarPersonasOperationCompleted == null)) {
                this.listarPersonasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarPersonasOperationCompleted);
            }
            this.InvokeAsync("listarPersonas", new object[] {
                        iduser}, this.listarPersonasOperationCompleted, userState);
        }
        
        private void OnlistarPersonasOperationCompleted(object arg) {
            if ((this.listarPersonasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarPersonasCompleted(this, new listarPersonasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool eliminarPersona([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] persona persona) {
            object[] results = this.Invoke("eliminarPersona", new object[] {
                        persona});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarPersonaAsync(persona persona) {
            this.eliminarPersonaAsync(persona, null);
        }
        
        /// <remarks/>
        public void eliminarPersonaAsync(persona persona, object userState) {
            if ((this.eliminarPersonaOperationCompleted == null)) {
                this.eliminarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarPersonaOperationCompleted);
            }
            this.InvokeAsync("eliminarPersona", new object[] {
                        persona}, this.eliminarPersonaOperationCompleted, userState);
        }
        
        private void OneliminarPersonaOperationCompleted(object arg) {
            if ((this.eliminarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarPersonaCompleted(this, new eliminarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool eliminarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user usuario) {
            object[] results = this.Invoke("eliminarUsuario", new object[] {
                        usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarUsuarioAsync(user usuario) {
            this.eliminarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void eliminarUsuarioAsync(user usuario, object userState) {
            if ((this.eliminarUsuarioOperationCompleted == null)) {
                this.eliminarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarUsuarioOperationCompleted);
            }
            this.InvokeAsync("eliminarUsuario", new object[] {
                        usuario}, this.eliminarUsuarioOperationCompleted, userState);
        }
        
        private void OneliminarUsuarioOperationCompleted(object arg) {
            if ((this.eliminarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarUsuarioCompleted(this, new eliminarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool editarPersona([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] persona persona) {
            object[] results = this.Invoke("editarPersona", new object[] {
                        persona});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarPersonaAsync(persona persona) {
            this.editarPersonaAsync(persona, null);
        }
        
        /// <remarks/>
        public void editarPersonaAsync(persona persona, object userState) {
            if ((this.editarPersonaOperationCompleted == null)) {
                this.editarPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarPersonaOperationCompleted);
            }
            this.InvokeAsync("editarPersona", new object[] {
                        persona}, this.editarPersonaOperationCompleted, userState);
        }
        
        private void OneditarPersonaOperationCompleted(object arg) {
            if ((this.editarPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarPersonaCompleted(this, new editarPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool registrarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user usuario) {
            object[] results = this.Invoke("registrarUsuario", new object[] {
                        usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void registrarUsuarioAsync(user usuario) {
            this.registrarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void registrarUsuarioAsync(user usuario, object userState) {
            if ((this.registrarUsuarioOperationCompleted == null)) {
                this.registrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("registrarUsuario", new object[] {
                        usuario}, this.registrarUsuarioOperationCompleted, userState);
        }
        
        private void OnregistrarUsuarioOperationCompleted(object arg) {
            if ((this.registrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarUsuarioCompleted(this, new registrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool editarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user usuario) {
            object[] results = this.Invoke("editarUsuario", new object[] {
                        usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void editarUsuarioAsync(user usuario) {
            this.editarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void editarUsuarioAsync(user usuario, object userState) {
            if ((this.editarUsuarioOperationCompleted == null)) {
                this.editarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarUsuarioOperationCompleted);
            }
            this.InvokeAsync("editarUsuario", new object[] {
                        usuario}, this.editarUsuarioOperationCompleted, userState);
        }
        
        private void OneditarUsuarioOperationCompleted(object arg) {
            if ((this.editarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarUsuarioCompleted(this, new editarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarFormulario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] formulario form, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user user, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool @return, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("registrarFormulario", new object[] {
                        form,
                        user});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void registrarFormularioAsync(formulario form, user user) {
            this.registrarFormularioAsync(form, user, null);
        }
        
        /// <remarks/>
        public void registrarFormularioAsync(formulario form, user user, object userState) {
            if ((this.registrarFormularioOperationCompleted == null)) {
                this.registrarFormularioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarFormularioOperationCompleted);
            }
            this.InvokeAsync("registrarFormulario", new object[] {
                        form,
                        user}, this.registrarFormularioOperationCompleted, userState);
        }
        
        private void OnregistrarFormularioOperationCompleted(object arg) {
            if ((this.registrarFormularioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarFormularioCompleted(this, new registrarFormularioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public empleado Validar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string privilegio) {
            object[] results = this.Invoke("Validar", new object[] {
                        dni,
                        pass,
                        privilegio});
            return ((empleado)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarAsync(string dni, string pass, string privilegio) {
            this.ValidarAsync(dni, pass, privilegio, null);
        }
        
        /// <remarks/>
        public void ValidarAsync(string dni, string pass, string privilegio, object userState) {
            if ((this.ValidarOperationCompleted == null)) {
                this.ValidarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarOperationCompleted);
            }
            this.InvokeAsync("Validar", new object[] {
                        dni,
                        pass,
                        privilegio}, this.ValidarOperationCompleted, userState);
        }
        
        private void OnValidarOperationCompleted(object arg) {
            if ((this.ValidarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarCompleted(this, new ValidarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Registrar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string apellidos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombres, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string privilegio) {
            object[] results = this.Invoke("Registrar", new object[] {
                        dni,
                        pass,
                        apellidos,
                        nombres,
                        privilegio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarAsync(string dni, string pass, string apellidos, string nombres, string privilegio) {
            this.RegistrarAsync(dni, pass, apellidos, nombres, privilegio, null);
        }
        
        /// <remarks/>
        public void RegistrarAsync(string dni, string pass, string apellidos, string nombres, string privilegio, object userState) {
            if ((this.RegistrarOperationCompleted == null)) {
                this.RegistrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarOperationCompleted);
            }
            this.InvokeAsync("Registrar", new object[] {
                        dni,
                        pass,
                        apellidos,
                        nombres,
                        privilegio}, this.RegistrarOperationCompleted, userState);
        }
        
        private void OnRegistrarOperationCompleted(object arg) {
            if ((this.RegistrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarCompleted(this, new RegistrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicios.desgo.com.ec/", ResponseNamespace="http://servicios.desgo.com.ec/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user user, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool @return, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("registrarUser", new object[] {
                        user});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void registrarUserAsync(user user) {
            this.registrarUserAsync(user, null);
        }
        
        /// <remarks/>
        public void registrarUserAsync(user user, object userState) {
            if ((this.registrarUserOperationCompleted == null)) {
                this.registrarUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarUserOperationCompleted);
            }
            this.InvokeAsync("registrarUser", new object[] {
                        user}, this.registrarUserOperationCompleted, userState);
        }
        
        private void OnregistrarUserOperationCompleted(object arg) {
            if ((this.registrarUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarUserCompleted(this, new registrarUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class user {
        
        private string cONTRASENIA_USUARIOField;
        
        private string eMPRESA_USUARIOField;
        
        private int iD_PERSONAField;
        
        private bool iD_PERSONAFieldSpecified;
        
        private int iD_TIPOUSUARIOField;
        
        private bool iD_TIPOUSUARIOFieldSpecified;
        
        private int iD_USUARIOField;
        
        private bool iD_USUARIOFieldSpecified;
        
        private persona personaField;
        
        private int sALT_USUARIOField;
        
        private bool sALT_USUARIOFieldSpecified;
        
        private tipoUsuario tipoUsuarioField;
        
        private string uSUARIO_USUARIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTRASENIA_USUARIO {
            get {
                return this.cONTRASENIA_USUARIOField;
            }
            set {
                this.cONTRASENIA_USUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPRESA_USUARIO {
            get {
                return this.eMPRESA_USUARIOField;
            }
            set {
                this.eMPRESA_USUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_PERSONA {
            get {
                return this.iD_PERSONAField;
            }
            set {
                this.iD_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_PERSONASpecified {
            get {
                return this.iD_PERSONAFieldSpecified;
            }
            set {
                this.iD_PERSONAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_TIPOUSUARIO {
            get {
                return this.iD_TIPOUSUARIOField;
            }
            set {
                this.iD_TIPOUSUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_TIPOUSUARIOSpecified {
            get {
                return this.iD_TIPOUSUARIOFieldSpecified;
            }
            set {
                this.iD_TIPOUSUARIOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_USUARIO {
            get {
                return this.iD_USUARIOField;
            }
            set {
                this.iD_USUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_USUARIOSpecified {
            get {
                return this.iD_USUARIOFieldSpecified;
            }
            set {
                this.iD_USUARIOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public persona persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SALT_USUARIO {
            get {
                return this.sALT_USUARIOField;
            }
            set {
                this.sALT_USUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SALT_USUARIOSpecified {
            get {
                return this.sALT_USUARIOFieldSpecified;
            }
            set {
                this.sALT_USUARIOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoUsuario tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USUARIO_USUARIO {
            get {
                return this.uSUARIO_USUARIOField;
            }
            set {
                this.uSUARIO_USUARIOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class persona {
        
        private string cARGO_PERSONAField;
        
        private string cEDULA_PERSONAField;
        
        private string cORREO_PERSONAField;
        
        private string eMPRESA_PERSONAField;
        
        private string fOTO_PERSONAField;
        
        private int iD_PERSONAField;
        
        private bool iD_PERSONAFieldSpecified;
        
        private string pAPELLIDO_PERSONAField;
        
        private string pNOMBRE_PERSONAField;
        
        private string pROFESION_PERSONAField;
        
        private string sAPELLIDO_PERSONAField;
        
        private string sNOMBRE_PERSONAField;
        
        private string tELEFONO_PERSONAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CARGO_PERSONA {
            get {
                return this.cARGO_PERSONAField;
            }
            set {
                this.cARGO_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CEDULA_PERSONA {
            get {
                return this.cEDULA_PERSONAField;
            }
            set {
                this.cEDULA_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CORREO_PERSONA {
            get {
                return this.cORREO_PERSONAField;
            }
            set {
                this.cORREO_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPRESA_PERSONA {
            get {
                return this.eMPRESA_PERSONAField;
            }
            set {
                this.eMPRESA_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FOTO_PERSONA {
            get {
                return this.fOTO_PERSONAField;
            }
            set {
                this.fOTO_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_PERSONA {
            get {
                return this.iD_PERSONAField;
            }
            set {
                this.iD_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_PERSONASpecified {
            get {
                return this.iD_PERSONAFieldSpecified;
            }
            set {
                this.iD_PERSONAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAPELLIDO_PERSONA {
            get {
                return this.pAPELLIDO_PERSONAField;
            }
            set {
                this.pAPELLIDO_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PNOMBRE_PERSONA {
            get {
                return this.pNOMBRE_PERSONAField;
            }
            set {
                this.pNOMBRE_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROFESION_PERSONA {
            get {
                return this.pROFESION_PERSONAField;
            }
            set {
                this.pROFESION_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SAPELLIDO_PERSONA {
            get {
                return this.sAPELLIDO_PERSONAField;
            }
            set {
                this.sAPELLIDO_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNOMBRE_PERSONA {
            get {
                return this.sNOMBRE_PERSONAField;
            }
            set {
                this.sNOMBRE_PERSONAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEFONO_PERSONA {
            get {
                return this.tELEFONO_PERSONAField;
            }
            set {
                this.tELEFONO_PERSONAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class empleado {
        
        private string apellidosField;
        
        private string contraseñaField;
        
        private string dniField;
        
        private string nombresField;
        
        private string privilegioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string privilegio {
            get {
                return this.privilegioField;
            }
            set {
                this.privilegioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class viviendaF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class responsablesF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class mejoraF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class mapaF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class limitesF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class direccionDDPLote {
        
        private string cALLEP_DLOTEField;
        
        private int iD_DLOTEField;
        
        private bool iD_DLOTEFieldSpecified;
        
        private string iNTERSECCION_DLOTEField;
        
        private string nO_DLOTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CALLEP_DLOTE {
            get {
                return this.cALLEP_DLOTEField;
            }
            set {
                this.cALLEP_DLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_DLOTE {
            get {
                return this.iD_DLOTEField;
            }
            set {
                this.iD_DLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_DLOTESpecified {
            get {
                return this.iD_DLOTEFieldSpecified;
            }
            set {
                this.iD_DLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INTERSECCION_DLOTE {
            get {
                return this.iNTERSECCION_DLOTEField;
            }
            set {
                this.iNTERSECCION_DLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NO_DLOTE {
            get {
                return this.nO_DLOTEField;
            }
            set {
                this.nO_DLOTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class dDescriptivosPredioIULote {
        
        private int iD_DDPLOTEField;
        
        private bool iD_DDPLOTEFieldSpecified;
        
        private int iD_DLOTEField;
        
        private bool iD_DLOTEFieldSpecified;
        
        private string nOMBREEDIFICIO_DDPLOTEField;
        
        private string nOMBRESECTOR_DDPLOTEField;
        
        private string rEGIMENTENECIA_DDPLOTEField;
        
        private string tIPOPREDIO_DDPLOTEField;
        
        private string uSOPREDIO_DDPLOTEField;
        
        private direccionDDPLote dDPLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_DDPLOTE {
            get {
                return this.iD_DDPLOTEField;
            }
            set {
                this.iD_DDPLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_DDPLOTESpecified {
            get {
                return this.iD_DDPLOTEFieldSpecified;
            }
            set {
                this.iD_DDPLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_DLOTE {
            get {
                return this.iD_DLOTEField;
            }
            set {
                this.iD_DLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_DLOTESpecified {
            get {
                return this.iD_DLOTEFieldSpecified;
            }
            set {
                this.iD_DLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBREEDIFICIO_DDPLOTE {
            get {
                return this.nOMBREEDIFICIO_DDPLOTEField;
            }
            set {
                this.nOMBREEDIFICIO_DDPLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRESECTOR_DDPLOTE {
            get {
                return this.nOMBRESECTOR_DDPLOTEField;
            }
            set {
                this.nOMBRESECTOR_DDPLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGIMENTENECIA_DDPLOTE {
            get {
                return this.rEGIMENTENECIA_DDPLOTEField;
            }
            set {
                this.rEGIMENTENECIA_DDPLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPOPREDIO_DDPLOTE {
            get {
                return this.tIPOPREDIO_DDPLOTEField;
            }
            set {
                this.tIPOPREDIO_DDPLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USOPREDIO_DDPLOTE {
            get {
                return this.uSOPREDIO_DDPLOTEField;
            }
            set {
                this.uSOPREDIO_DDPLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public direccionDDPLote dDPLote {
            get {
                return this.dDPLoteField;
            }
            set {
                this.dDPLoteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class identificacionUF {
        
        private string cLAVECATASTRALANTIGUO_IULOTEField;
        
        private string cLAVECATASTRALNUEVO_IULOTEField;
        
        private int iD_DDPLOTEField;
        
        private bool iD_DDPLOTEFieldSpecified;
        
        private int iD_IULOTEField;
        
        private bool iD_IULOTEFieldSpecified;
        
        private string nUMEROPREDIO_IULOTEField;
        
        private dDescriptivosPredioIULote dDescriptivosPredio_IULoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLAVECATASTRALANTIGUO_IULOTE {
            get {
                return this.cLAVECATASTRALANTIGUO_IULOTEField;
            }
            set {
                this.cLAVECATASTRALANTIGUO_IULOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLAVECATASTRALNUEVO_IULOTE {
            get {
                return this.cLAVECATASTRALNUEVO_IULOTEField;
            }
            set {
                this.cLAVECATASTRALNUEVO_IULOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_DDPLOTE {
            get {
                return this.iD_DDPLOTEField;
            }
            set {
                this.iD_DDPLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_DDPLOTESpecified {
            get {
                return this.iD_DDPLOTEFieldSpecified;
            }
            set {
                this.iD_DDPLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_IULOTE {
            get {
                return this.iD_IULOTEField;
            }
            set {
                this.iD_IULOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_IULOTESpecified {
            get {
                return this.iD_IULOTEFieldSpecified;
            }
            set {
                this.iD_IULOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMEROPREDIO_IULOTE {
            get {
                return this.nUMEROPREDIO_IULOTEField;
            }
            set {
                this.nUMEROPREDIO_IULOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dDescriptivosPredioIULote dDescriptivosPredio_IULote {
            get {
                return this.dDescriptivosPredio_IULoteField;
            }
            set {
                this.dDescriptivosPredio_IULoteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class identificacionLF {
        
        private string fORMAADQUISICIONField;
        
        private int iD_COP_ILLOTEField;
        
        private bool iD_COP_ILLOTEFieldSpecified;
        
        private int iD_DIR_ILLOTEField;
        
        private bool iD_DIR_ILLOTEFieldSpecified;
        
        private int iD_DOC_ILLOTEField;
        
        private bool iD_DOC_ILLOTEFieldSpecified;
        
        private int iD_ILLOTEField;
        
        private bool iD_ILLOTEFieldSpecified;
        
        private int iD_PRE_ILLOTEField;
        
        private bool iD_PRE_ILLOTEFieldSpecified;
        
        private int iD_PROField;
        
        private bool iD_PROFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FORMAADQUISICION {
            get {
                return this.fORMAADQUISICIONField;
            }
            set {
                this.fORMAADQUISICIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_COP_ILLOTE {
            get {
                return this.iD_COP_ILLOTEField;
            }
            set {
                this.iD_COP_ILLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_COP_ILLOTESpecified {
            get {
                return this.iD_COP_ILLOTEFieldSpecified;
            }
            set {
                this.iD_COP_ILLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_DIR_ILLOTE {
            get {
                return this.iD_DIR_ILLOTEField;
            }
            set {
                this.iD_DIR_ILLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_DIR_ILLOTESpecified {
            get {
                return this.iD_DIR_ILLOTEFieldSpecified;
            }
            set {
                this.iD_DIR_ILLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_DOC_ILLOTE {
            get {
                return this.iD_DOC_ILLOTEField;
            }
            set {
                this.iD_DOC_ILLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_DOC_ILLOTESpecified {
            get {
                return this.iD_DOC_ILLOTEFieldSpecified;
            }
            set {
                this.iD_DOC_ILLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_ILLOTE {
            get {
                return this.iD_ILLOTEField;
            }
            set {
                this.iD_ILLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_ILLOTESpecified {
            get {
                return this.iD_ILLOTEFieldSpecified;
            }
            set {
                this.iD_ILLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_PRE_ILLOTE {
            get {
                return this.iD_PRE_ILLOTEField;
            }
            set {
                this.iD_PRE_ILLOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_PRE_ILLOTESpecified {
            get {
                return this.iD_PRE_ILLOTEFieldSpecified;
            }
            set {
                this.iD_PRE_ILLOTEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_PRO {
            get {
                return this.iD_PROField;
            }
            set {
                this.iD_PROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_PROSpecified {
            get {
                return this.iD_PROFieldSpecified;
            }
            set {
                this.iD_PROFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class graficosPF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class elementosCF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class economicaF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class caracterizacionLF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class caracterizacionCF {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class formulario {
        
        private caracterizacionCF caracterizacionC_FField;
        
        private caracterizacionLF caracterizacionL_FField;
        
        private int codigo_FField;
        
        private bool codigo_FFieldSpecified;
        
        private economicaF economica_FField;
        
        private elementosCF elementosC_FField;
        
        private int estado_FField;
        
        private bool estado_FFieldSpecified;
        
        private graficosPF graficosP_FField;
        
        private int idFormularioField;
        
        private bool idFormularioFieldSpecified;
        
        private int idUsuario_FField;
        
        private bool idUsuario_FFieldSpecified;
        
        private identificacionLF identificacionL_FField;
        
        private identificacionUF identificacionU_FField;
        
        private limitesF limites_FField;
        
        private mapaF mapa_FField;
        
        private mejoraF mejora_FField;
        
        private responsablesF responsables_FField;
        
        private viviendaF vivienda_FField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public caracterizacionCF caracterizacionC_F {
            get {
                return this.caracterizacionC_FField;
            }
            set {
                this.caracterizacionC_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public caracterizacionLF caracterizacionL_F {
            get {
                return this.caracterizacionL_FField;
            }
            set {
                this.caracterizacionL_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigo_F {
            get {
                return this.codigo_FField;
            }
            set {
                this.codigo_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigo_FSpecified {
            get {
                return this.codigo_FFieldSpecified;
            }
            set {
                this.codigo_FFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public economicaF economica_F {
            get {
                return this.economica_FField;
            }
            set {
                this.economica_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public elementosCF elementosC_F {
            get {
                return this.elementosC_FField;
            }
            set {
                this.elementosC_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estado_F {
            get {
                return this.estado_FField;
            }
            set {
                this.estado_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estado_FSpecified {
            get {
                return this.estado_FFieldSpecified;
            }
            set {
                this.estado_FFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public graficosPF graficosP_F {
            get {
                return this.graficosP_FField;
            }
            set {
                this.graficosP_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFormulario {
            get {
                return this.idFormularioField;
            }
            set {
                this.idFormularioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idFormularioSpecified {
            get {
                return this.idFormularioFieldSpecified;
            }
            set {
                this.idFormularioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario_F {
            get {
                return this.idUsuario_FField;
            }
            set {
                this.idUsuario_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuario_FSpecified {
            get {
                return this.idUsuario_FFieldSpecified;
            }
            set {
                this.idUsuario_FFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public identificacionLF identificacionL_F {
            get {
                return this.identificacionL_FField;
            }
            set {
                this.identificacionL_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public identificacionUF identificacionU_F {
            get {
                return this.identificacionU_FField;
            }
            set {
                this.identificacionU_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public limitesF limites_F {
            get {
                return this.limites_FField;
            }
            set {
                this.limites_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mapaF mapa_F {
            get {
                return this.mapa_FField;
            }
            set {
                this.mapa_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mejoraF mejora_F {
            get {
                return this.mejora_FField;
            }
            set {
                this.mejora_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public responsablesF responsables_F {
            get {
                return this.responsables_FField;
            }
            set {
                this.responsables_FField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public viviendaF vivienda_F {
            get {
                return this.vivienda_FField;
            }
            set {
                this.vivienda_FField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.desgo.com.ec/")]
    public partial class tipoUsuario {
        
        private int iD_TIPOUSUARIOField;
        
        private bool iD_TIPOUSUARIOFieldSpecified;
        
        private string nIVEL_TIPOUSUARIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_TIPOUSUARIO {
            get {
                return this.iD_TIPOUSUARIOField;
            }
            set {
                this.iD_TIPOUSUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_TIPOUSUARIOSpecified {
            get {
                return this.iD_TIPOUSUARIOFieldSpecified;
            }
            set {
                this.iD_TIPOUSUARIOFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIVEL_TIPOUSUARIO {
            get {
                return this.nIVEL_TIPOUSUARIOField;
            }
            set {
                this.nIVEL_TIPOUSUARIOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public user Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((user)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarPersonaCompletedEventHandler(object sender, buscarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public user Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((user)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarRolesCompletedEventHandler(object sender, listarRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tipoUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tipoUsuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarUsuariosCompletedEventHandler(object sender, listarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public user[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((user[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void listarPersonasCompletedEventHandler(object sender, listarPersonasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarPersonasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarPersonasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public persona[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((persona[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarPersonaCompletedEventHandler(object sender, eliminarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void eliminarUsuarioCompletedEventHandler(object sender, eliminarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarPersonaCompletedEventHandler(object sender, editarPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registrarUsuarioCompletedEventHandler(object sender, registrarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void editarUsuarioCompletedEventHandler(object sender, editarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registrarFormularioCompletedEventHandler(object sender, registrarFormularioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarFormularioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarFormularioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidarCompletedEventHandler(object sender, ValidarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RegistrarCompletedEventHandler(object sender, RegistrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void registrarUserCompletedEventHandler(object sender, registrarUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591